---
- name: Set custom DNS configuration
  hosts: masters, workers
  become: yes

  tasks:
    - name: Replace DNS config with custom servers
      blockinfile:
        path: /etc/systemd/resolved.conf
        marker: "# {mark} ANSIBLE MANAGED DNS CONFIG"
        block: |
          [Resolve]
          DNS= 185.51.200.2 178.22.122.100
          FallbackDNS= 8.8.8.8 1.1.1.1
        create: yes

    - name: Restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted

